FUNiX-Tech/edx-platform

- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/testing.txt
Change requirements versions for compatibility with assignmentxblock
> fix: change package version to prevent conflict to boto

- lms/djangoapps/funix_portal_api/views.py
- lms/urls.py
api that allows to grade assignmentxblock.
> feature: grade assignmetn api

- common/djangoapps/student/views/dashboard.py
- lms/djangoapps/learner_home/serializers.py
- lms/djangoapps/learner_home/views.py
- openedx/features/funix_relative_date/views.py
- Add a complete block to the learn home init API and remove redundant data.
- Comment out the dashboard and navigate to the micro frontend (MFE) dashboard.
> Feature/block complete dashboard , add block complete api and navigate MFE dashboard

- conf/locale/vi/LC_MESSAGES/django.po
- lms/djangoapps/funix_portal_api/views.py
- lms/urls.py
Added translation texts for learning project xblock. 
Changed term assignment to learning project.
> feat (learning project xblock translation): add translate text

- lms/djangoapps/feedback/views.py
- openedx/core/djangoapps/user_authn/views/register.py
> fix: change site domain portal

- cms/envs/common.py
- lms/envs/common.py
Set vi as default language according to QC.
> feature (i18n): set default language to vi

- lms/djangoapps/course_api/blocks/transformers/block_completion.py
- fix err not time date (xblock complete)
- not view course
> fix: not type block complete

- lms/templates/problem.html
- fix css , remove class problem-error
> fix : remove class problem-error

- openedx/core/djangoapps/chatbot/api.py
- openedx/core/djangoapps/chatbot/urls.py
- openedx/core/djangoapps/chatbot/views.py
Fix some error in chatbot view.
> fix (chatbot): view error

- openedx/core/djangoapps/user_authn/views/login.py
- remove validate not email (login form)
> chore : remove validate not email

- conf/locale/vi/LC_MESSAGES/django.po
> chore : add more tranls

- lms/djangoapps/funix_portal_api/views.py
- lms/static/sass/_funix.scss
- lms/static/sass/lms-course.scss
- xmodule/css/html/display.scss-old
- Styles for Unit lms.
- create student_code when create a user by api.
> Feature: unit lms styles

- lms/static/sass/_funix.scss
> fix (unit styles): anchor styles

- lms/static/sass/_funix.scss
Fix unit styles: remove span margin.
> fix (unit styles): remove span margin

- lms/static/sass/_funix.scss
> fix (unit ui): style i tag

- lms/static/sass/_funix.scss
> fix (unit style): heading tag

- xmodule/js/src/capa/display.js
> fix : focus problem render

- cms/static/sass/_funix-studio.scss
- cms/static/sass/studio-main-v1.scss
- lms/static/sass/_funix.scss
- lms/static/sass/lms-course.scss
- lms/templates/main.html
- Add info tags.
- style <details>, <table>, img.
- post message when click on <summary> tag to handle unit height when collapse/expand <details>.
- scss for lms and studio unit.
> Feature (unit components): add info tags, table styles, image styles

- lms/djangoapps/course_api/blocks/transformers/block_completion.py
> fix: get complete time

- cms/static/sass/_funix-studio.scss
fix (studio style): xblock header button icon
> fix (studio style): xblock header button icon

- lms/djangoapps/funix_portal_api/views.py
- lms/urls.py
Create portal_host api for  frontend app learning calling
> feat: create portal_host api

- lms/templates/problem.html
> feat: add api next_lesson

- cms/djangoapps/contentstore/views/component.py
> chore : remove print and update labxblock

- xmodule/video_module/video_module.py
Remove completion for video youtube rule
> fix: remove completion video youtube rule

- lms/static/sass/_funix.scss
> chore: lms image scss

- cms/djangoapps/contentstore/views/funix_remove_inline_styles.py
- cms/static/sass/_funix-studio.scss
- cms/templates/funix_remove_inline_style.html
- lms/static/sass/_funix.scss
Fix unit image ratio studio and lms. Update handler errors remove inline styles.
> Fix unit image ratio studio and lms. Update handler errors remove inline styles.

- cms/djangoapps/contentstore/views/funix_remove_inline_styles.py
- cms/static/sass/_funix-studio.scss
- lms/static/sass/_funix.scss
Add tags that will be remove styles.
Fix strong  span font weight
> Add tags that will be remove styles

- lms/djangoapps/funix_portal_api/views.py
- lms/urls.py
Create api to return redirect_url with course key +/- course location provided.
> feature: get resume url api

- lms/static/sass/_funix-base.scss
- lms/static/sass/_funix-single-quiz.scss
- lms/static/sass/_funix.scss
Please review my code: Fix single quiz UI.
> fix: single quiz style

- lms/djangoapps/discussion/rest_api/api.py
- openedx/core/djangoapps/discussions/migrations/0018_discussionTag.py
- openedx/core/djangoapps/discussions/models.py
> feat: add more tags discussion

- lms/djangoapps/discussion/rest_api/api.py
- openedx/core/djangoapps/discussions/migrations/0019_remove_discussion_actions.py
- openedx/core/djangoapps/discussions/models.py
- Bug fix : not action menu discussion and remove thread best
> fix: bug not action menu and remove thread best

- cms/djangoapps/contentstore/views/component.py
> chore: update labXblock

- openedx/core/djangoapps/chatbot/serializer.py
- openedx/core/djangoapps/chatbot/urls.py
- openedx/core/djangoapps/chatbot/views.py
Chatbot session. 
Convert markdown response message to html.
> feature: chatbot session and display markdown

- cms/static/sass/funix/base/_mixins.scss
- cms/static/sass/funix/base/_variables.scss
- cms/static/sass/funix/unit/_build.scss
- cms/static/sass/funix/unit/components/_xmodule-HtmlBlock.scss
- cms/static/sass/funix/unit/components/_xmodule-ProblemBlock.scss
- cms/static/sass/funix/unit/components/_xmodule-VideoBlock.scss
- cms/static/sass/funix/unit/mixins/_details.scss
- cms/static/sass/funix/unit/mixins/_image.scss
- cms/static/sass/funix/unit/mixins/_problem.scss
- cms/static/sass/funix/unit/mixins/_table.scss
- cms/static/sass/funix/unit/mixins/_typography.scss
- lms/static/sass/funix/unit/_build.scss
- lms/static/sass/funix/unit/components/_xmodule-HtmlBlock.scss
- lms/static/sass/funix/unit/components/_xmodule-VideoBlock.scss
- lms/static/sass/funix/unit/mixins/_image.scss
- lms/static/sass/funix/unit/mixins/_table.scss
- lms/static/sass/funix/unit/mixins/_typography.scss
New design typography for unit lms and studio.
> Feature/new design UI

- lms/djangoapps/course_home_api/course_metadata/views.py
- lms/djangoapps/courseware/courses.py
- lms/djangoapps/learner_home/serializers.py
- Sort list course Dashboard page
> feat : last history course dashboard

- lms/static/sass/funix/explore_course/_build.scss
- lms/static/sass/funix/explore_course/_explore-course.scss
- lms/static/sass/lms-main-v1.scss
- lms/templates/discovery/course_card.underscore
Description:
- responsive layout in explore courses
- restore search bar
> fix: responsive layout in explore courses

- lms/static/sass/funix/explore_course/_explore-course.scss
- Adjust image size in course card
> fix: adjust image size in course card

- cms/static/sass/funix/base/_mixins.scss
- cms/static/sass/funix/base/_variables.scss
- cms/static/sass/funix/unit/_build.scss
- cms/static/sass/funix/unit/mixins/_details.scss
- cms/static/sass/funix/unit/mixins/_table.scss
- cms/static/sass/funix/unit/mixins/_typography.scss
- lms/static/sass/funix/base/_mixins.scss
- lms/static/sass/funix/base/_variables.scss
- lms/static/sass/funix/unit/components/_xmodule-HtmlBlock.scss
Unit typo: change pt to rem, em, table responsive lms.
> feature (unit design): change pt to rem, em, table responsive lms

- lms/static/sass/funix/explore_course/_explore-course.scss
- lms/templates/index.html
- Adjust layout of search message and search input
> fix: adjust layout of search input and search message

- cms/static/sass/funix/base/_mixins.scss
- cms/static/sass/funix/base/_variables.scss
- cms/static/sass/funix/unit/_build.scss
- cms/static/sass/funix/unit/components/_xmodule-HtmlBlock.scss
- cms/static/sass/funix/unit/components/_xmodule-ProblemBlock.scss
- cms/static/sass/funix/unit/components/_xmodule-VideoBlock.scss
- cms/static/sass/funix/unit/mixins/_details.scss
- cms/static/sass/funix/unit/mixins/_image.scss
- cms/static/sass/funix/unit/mixins/_problem.scss
- cms/static/sass/funix/unit/mixins/_table.scss
- cms/static/sass/funix/unit/mixins/_typography.scss
- lms/static/sass/funix/base/_mixins.scss
- lms/static/sass/funix/base/_variables.scss
- lms/static/sass/funix/unit/_build.scss
- lms/static/sass/funix/unit/components/_xmodule-HtmlBlock.scss
- lms/static/sass/funix/unit/components/_xmodule-VideoBlock.scss
- lms/static/sass/funix/unit/mixins/_image.scss
- lms/static/sass/funix/unit/mixins/_table.scss
- lms/static/sass/funix/unit/mixins/_typography.scss
- openedx/core/djangoapps/chatbot/serializer.py
Feature: new unit design typography, Fix: chatbot.
> Feature: new unit design typography, Fix: chatbot

- lms/djangoapps/learner_home/serializers.py
- Fix bug : not date history dashboard
> fix : not date history dashboard

- lms/templates/problem.html
- xmodule/capa/templates/matchinggroup.html
fix: css style html tag, fix button in multi quiz
> fix: css style html tag

- lms/static/sass/_header.scss
- lms/static/sass/shared/_footer.scss
Fix: change font to roboto 
fix 2 file lms/static/sass/_header.scss và lms/static/sass/shared/_footer.scss
> Fix: change font to roboto

- lms/static/sass/_header.scss
- lms/static/sass/funix/explore_course/_explore-course.scss
- lms/static/sass/shared/_footer.scss
- The _header file in static/sass/_header.sass has being modified heavily for unknown reason. Reverting back to the original file
> fix: _header sass file

- lms/static/sass/_header.scss
- lms/static/sass/funix/base/_variables.scss
- lms/static/sass/funix/explore_course/_course-list.scss
- lms/static/sass/funix/explore_course/_explore-course.scss
- lms/static/sass/funix/explore_course/_header.scss
- lms/static/sass/funix/explore_course/_search-input.scss
- lms/static/sass/views/_homepage.scss
> ui: update course-list layout in explore courses

- lms/templates/problem.html
> feat : problem success not answer

- lms/static/sass/funix/explore_course/_explore-course.scss
- lms/static/sass/funix/home/_header.scss
> ui: add position fixed on header

- cms/envs/devstack.py
- lms/envs/devstack.py
-Fix upload explore course img
> fix: fix upload image explore course

- cms/djangoapps/contentstore/signals/handlers.py
fix not update image when upload image in studio
> fix : fix not update image

- lms/static/sass/_header.scss
- lms/static/sass/funix/home/_build.scss
- lms/static/sass/funix/home/_navbar.scss
- lms/templates/header/navbar-authenticated.html
- Fix explore-course's header for authenticated user
> fix: fix explore-course header of authenticated user

- lms/static/sass/_header.scss
- lms/static/sass/funix/home/_header.scss
> fix: mobile-menu position

- lms/static/sass/funix/home/_header.scss
- lms/templates/navigation/bootstrap/navbar-authenticated.html
- fix mobile menu to fixed position
> fix: fix mobile menu to fixed position

- lms/static/js/header/header.js
- lms/static/sass/funix/base/_variables.scss
- lms/static/sass/funix/explore_course/_course-list.scss
- lms/static/sass/funix/explore_course/_explore-course.scss
- lms/static/sass/funix/explore_course/_search-input.scss
- lms/static/sass/funix/home/_course-list.scss
- lms/static/sass/funix/home/_footer.scss
- lms/static/sass/funix/home/_header.scss
- lms/templates/header/navbar-not-authenticated.html
- New responsive layout of explore-courses page
> ui: adjust to new ui design

- cms/djangoapps/contentstore/signals/handlers.py
- cms/envs/devstack.py
- lms/envs/devstack.py
-Fix upload image in explore course page
> fix: fix upload image no update in course explore page

- lms/static/sass/funix/explore_course/_course-list.scss
- Readjust responsive breakpoint of course-list
> fix: readjust breakpoint responsive course-list

- lms/templates/discovery/course_card.underscore
- Add default image when courses don't have one
> fix: display default image if courses don't have one

- lms/static/sass/funix/explore_course/_course-list.scss
- lms/static/sass/views/_homepage.scss
- add border radius top for course_card, centering the learn-more element when hover into course_card
> fix: add border radius top for course_card, centering the learn-more element

- cms/djangoapps/contentstore/signals/handlers.py
> fix: fix delay update course

- cms/djangoapps/contentstore/signals/handlers.py
-Continue debug fix delay update course
> fix : continue fix delay

- cms/djangoapps/contentstore/signals/handlers.py
> fix: fix upload image and delay course

- lms/static/js/discovery/discovery_factory.js
- lms/static/js/discovery/models/search_state.js
- lms/static/js/discovery/views/search_form.js
- lms/static/sass/funix/base/_variables.scss
- lms/static/sass/funix/explore_course/_course-list.scss
- lms/static/sass/funix/explore_course/_search-input.scss
- lms/static/sass/funix/home/_header.scss
- lms/static/sass/multicourse/_courses.scss
- lms/templates/courseware/courses.html
- Add search result
- Change hover and active color
> ui: add search-message, adjust hover and active color

- cms/static/sass/funix/unit/mixins/_details.scss
- cms/static/sass/funix/unit/mixins/_typography.scss
- lms/static/sass/funix/unit/mixins/_details.scss
- lms/static/sass/funix/unit/mixins/_typography.scss
chore: text align justify more tags
> chore: text align justify more tags

- cms/static/sass/funix/unit/mixins/_details.scss
- cms/static/sass/funix/unit/mixins/_table.scss
- cms/static/sass/funix/unit/mixins/_typography.scss
- common/static/css/tinymce-studio-content.css
- lms/static/sass/funix/unit/mixins/_details.scss
- lms/static/sass/funix/unit/mixins/_table.scss
- lms/static/sass/funix/unit/mixins/_typography.scss
- xmodule/js/src/html/edit.js
> fix: justify text, studio editor

- lms/templates/problem.html
- xmodule/capa/inputtypes.py
- xmodule/capa/responsetypes.py
- xmodule/capa/templates/matchinggroup.html
- xmodule/templates/problem/matchinginput.yaml
- xmodule/templates/problem/quiz_custom.yaml
feature: add explanation for matching quiz
> feat: add explanation for matching quiz

- lms/static/sass/funix/explore_course/_search-input.scss
- Fix stutter effect when hover into search input
> fix: stutter effect when hover and click on search input

- lms/static/sass/funix/unit/_build.scss
> fix: content margin top

- lms/templates/problem.html
- xmodule/js/src/capa/display.js
> fix : quiz status

- lms/djangoapps/courseware/views/views.py
> chore: change url redirect mfe about

- lms/static/js/header/header.js
- handle header's case when expanding the view while mobile-menu is being opened
> fix: handle header case when expanding the view while mobile-menu is being opened

- lms/static/sass/funix/home/_header.scss
- Fix: vertically centering sign in button on header
> fix: vertically centering sign in button on header

- common/djangoapps/student/helpers.py
- lms/djangoapps/learner_home/serializers.py
- lms/djangoapps/learner_home/views.py
Add course begin url to init dashboard api.
> feature: add course begin url to dashboard init api

- common/djangoapps/student/helpers.py
- lms/djangoapps/learner_home/serializers.py
- lms/djangoapps/learner_home/views.py
fix: begin course button url staging
> fix: begin course button url staging

- lms/templates/main.html
> fix: unit bottom gap staging

- openedx/features/funix_relative_date/handlers.py
- Performance : comment FunixRelativeDateLibary re-schedule course
> feat : comment FunixRelativeDateLibary re-schedule course

- cms/envs/common.py
- cms/static/sass/funix/base/_variables.scss
- cms/static/sass/funix/unit/_build.scss
- cms/static/sass/funix/unit/components/_xmodule-TextBlock.scss/_TextBlock-videoComponent.scss
- common/static/css/tinymce-studio-content-funix.css
- common/static/css/tinymce-studio-content.css
- lms/static/sass/funix/base/_variables.scss
- lms/static/sass/funix/unit/_build.scss
- lms/static/sass/funix/unit/components/_xmodule-textBlock.scss/_textBlock-videoComponent.scss
- xmodule/templates/html/video_component.yaml
- Add video component as htmlBlock
> feat: add video component as htmlBlock

- cms/templates/about_course.html
- Change title template teacher
> chore : change name label

- cms/static/sass/funix/unit/components/_xmodule-TextBlock.scss/_TextBlock-videoComponent.scss
- common/static/css/tinymce-studio-content-funix.css
- Adjust styling in studio and editor
> fix: adjust styling in studio

- cms/static/sass/funix/base/_variables.scss
- cms/static/sass/funix/unit/components/_xmodule-TextBlock.scss/_TextBlock-videoComponent.scss
- common/static/css/tinymce-studio-content-funix.css
- common/static/css/tinymce-studio-content.css
- lms/static/sass/funix/base/_variables.scss
- lms/static/sass/funix/unit/components/_xmodule-textBlock.scss/_textBlock-videoComponent.scss
- lms/templates/courseware/courseware-chromeless.html
- xmodule/templates/html/video_component.yaml
- Add video component to CMS studio
> feat: add video component in studio

- cms/envs/common.py
- add funix custom tinymce styling file to config
> fix: add funix custom tinymce styling file to config

- lms/static/js/discovery/views/search_form.js
- lms/static/sass/funix/base/_variables.scss
- lms/static/sass/funix/explore_course/_course-list.scss
- lms/static/sass/funix/explore_course/_search-input.scss
- lms/templates/courseware/courses.html
- lms/templates/header/navbar-not-authenticated.html
> ui: change search input layout, change sign in icon
